# (opcional) elimina esta línea si quieres evitar el warning:
# version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      # Usa directamente las variables de Postgres (evita encadenar en .env)
      APP_ENV: ${APP_ENV:-production}
      APP_DB_HOST: ${APP_DB_HOST:-db}
      APP_DB_PORT: ${APP_DB_PORT:-5432}
      APP_DB_NAME: ${POSTGRES_DB}
      APP_DB_USER: ${POSTGRES_USER}
      APP_DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "${APP_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # esto se inyecta al stage de build de Vite
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api}
    container_name: front
    depends_on:
      app:
        condition: service_started
    ports:
      - "${FRONT_PORT:-8081}:80"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    depends_on:
      front:
        condition: service_started
      app:
        condition: service_started
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddydata:/data
      - caddyconfig:/config
    ports:
      - "80:80"
      - "443:443"
    environment:
      CADDY_DOMAIN: ${CADDY_DOMAIN}
      CADDY_EMAIL: ${CADDY_EMAIL}
    profiles: ["caddy"]
    restart: unless-stopped

volumes:
  dbdata:
  caddydata:
  caddyconfig:
