server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${APP_DB_HOST:db}:${APP_DB_PORT:5432}/${APP_DB_NAME:appdb}
    username: ${APP_DB_USER:appuser}
    password: ${APP_DB_PASS:app-secret}

  jpa:
    hibernate:
      ddl-auto: none          # NO tocar el esquema (ni crear, ni validar, ni actualizar)
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true  # crea flyway_schema_history aunque el schema no esté vacío
    baseline-version: 0
    clean-disabled: true       # evita "flyway clean" accidental

management:
  endpoints:
    web:
      exposure:
        include: health,info

